# Generated by Django 4.2.2 on 2023-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='lower_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('date', 'Date'), ('text', 'Text'), ('number', 'Number')], default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
